#!/bin/sh
set -e
package_name=arc-theme-breezed
case "$1" in
  remove)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/themes/Arc/gtk-3.0/gtk.css"
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/themes/Arc-Dark/gtk-3.0/gtk.css"
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/themes/Arc-Darker/gtk-3.0/gtk.css"
    ;;
  purge)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/themes/Arc/gtk-3.0/gtk.css"
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/themes/Arc-Dark/gtk-3.0/gtk.css"
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/themes/Arc-Darker/gtk-3.0/gtk.css"
;;
esac
exit 0
